# Generated by Django 4.2.17 on 2025-01-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Известные женщины', 'verbose_name_plural': 'Известные женщины'},
        ),
        migrations.RemoveIndex(
            model_name='women',
            name='women_women_time_cr_9f33c2_idx',
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['id'], name='women_women_id_9b7715_idx'),
        ),
    ]
